name: Author Kristen Maxwell
favicon: null
layout_spectrum: 0.49928
typography_spectrum: 0.25324
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f4f4'
    - '#025b61'
    - '#b1acb0'
    - '#c23b5c'
    - '#051a20'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
